Reject audit logs until index template exists
This prevents elasticsearch from inferring a suboptimal index schema
from incoming audit logs before we can create an index template.

diff --git a/addons/elasticsearch/elasticsearch.yaml b/addons/elasticsearch/elasticsearch.yaml
--- a/addons/elasticsearch/elasticsearch.yaml
+++ b/addons/elasticsearch/elasticsearch.yaml
@@ -32,6 +32,11 @@ spec:
     version: 1.32.0
     values: |
       ---
+      cluster:
+        config:
+          # Disable automatic creation of audit log indexes.
+          # This is intended to reject audit logs until their index template has been created. See data.hooks.postStart.
+          action.auto_create_index: "-kubernetes_audit*"
       client:
         heapSize: 1024m
         resources:
@@ -85,6 +90,16 @@ spec:
                 echo "Error within _template 'kubernetes_audit' creation - exiting"
                 exit 1
               fi
+            fi
+
+            # Enable automatic creation of all indexes.
+            # This re-enables the creation of audit log indexes now that their index template exists. See cluster.config.
+            RES_SETTINGS=$(curl -XPUT -s -o /dev/null -w '%{http_code}' ${CLIENT_URL}/_cluster/settings \
+              -H "Content-Type: application/json; charset=utf-8" \
+              -d '{"persistent": {"action.auto_create_index": "true"}}')
+            if [[ "${RES_SETTINGS}" != "200" ]]; then
+              echo "Error applying cluster settings - exiting"
+              exit 1
             fi
         heapSize: 3072m
         resources:
