(release/2) Remove elasticsearch requirement from fluentbit (#803)
* Remove elasticsearch requirement from fluentbit

This allows fluentbit to deploy without elasticsearch enabled. If a user
would like to disable elasticsearch and use an alternative log sink,
they would otherwise have to edit the fluentbit addon spec and remove
the dependency.

* Reject audit logs until index template exists

This prevents elasticsearch from inferring a suboptimal index schema
from incoming audit logs before we can create an index template.

* Collect kubeaddons controller logs during cleanup

This collects kubeaddons controller logs to
/tmp/kubernetes-base-addons/<testgroup>/ during the cleanup phase.

* Add delete upgrade strategy for Elasticsearch

Some changes to the data node StatefulSet can't be applied to an
existing resource, so we have to delete and recreate.

* Bump elasticsearch addon revision

diff --git a/addons/elasticsearch/elasticsearch.yaml b/addons/elasticsearch/elasticsearch.yaml
--- a/addons/elasticsearch/elasticsearch.yaml
+++ b/addons/elasticsearch/elasticsearch.yaml
@@ -10,9 +10,11 @@ metadata:
     # on the cluster, this hack will trigger re-queue on Addons until one exists.
     kubeaddons.mesosphere.io/hack-requires-defaultstorageclass: "true"
   annotations:
-    catalog.kubeaddons.mesosphere.io/addon-revision: "6.8.2-7"
+    catalog.kubeaddons.mesosphere.io/addon-revision: "6.8.2-8"
     appversion.kubeaddons.mesosphere.io/elasticsearch: "6.8.2"
     values.chart.helm.kubeaddons.mesosphere.io/elasticsearch: "https://raw.githubusercontent.com/helm/charts/6bfbc8018cd4440637b07c7559d5812e4d9db34d/stable/elasticsearch/values.yaml"
+    helm.kubeaddons.mesosphere.io/upgrade-strategy: "[{\"upgradeFrom\": \"<=6.8.2\", \"strategy\": \"delete\"}]"
+    helm2.kubeaddons.mesosphere.io/upgrade-strategy: "[{\"upgradeFrom\": \"<=6.8.2\", \"strategy\": \"delete\"}]"
 spec:
   kubernetes:
     minSupportedVersion: v1.15.0
@@ -32,6 +34,11 @@ spec:
     version: 1.32.0
     values: |
       ---
+      cluster:
+        config:
+          # Disable automatic creation of audit log indexes.
+          # This is intended to reject audit logs until their index template has been created. See data.hooks.postStart.
+          action.auto_create_index: "-kubernetes_audit*"
       client:
         heapSize: 1024m
         resources:
@@ -85,6 +92,16 @@ spec:
                 echo "Error within _template 'kubernetes_audit' creation - exiting"
                 exit 1
               fi
+            fi
+
+            # Enable automatic creation of all indexes.
+            # This re-enables the creation of audit log indexes now that their index template exists. See cluster.config.
+            RES_SETTINGS=$(curl -XPUT -s -o /dev/null -w '%{http_code}' ${CLIENT_URL}/_cluster/settings \
+              -H "Content-Type: application/json; charset=utf-8" \
+              -d '{"persistent": {"action.auto_create_index": "true"}}')
+            if [[ "${RES_SETTINGS}" != "200" ]]; then
+              echo "Error applying cluster settings - exiting"
+              exit 1
             fi
         heapSize: 3072m
         resources:
